name: ServerBalancer
version: 1.0
main: com.feliex.serverbalancer.ServerBalancer
api-version: 1.21
commands:
  server:
    description: 打開分流管理介面
    usage: /<command>
permissions:
  serverbalancer.admin:
    description: 使用管理指令
    default: op
