name: ServerBalancer
main: com.feliex.serverbalancer.ServerBalancer
version: 1.0
api-version: "1.21"
commands:
  server:
    description: 打開伺服器分流管理 GUI
permissions:
  serverbalancer.use:
    default: true
